site_name: Stereo Documentation
repo_url: https://github.com/suda/stereo
pages:
- Home: index.md
- Generating documents from CSV files: generating-from-csv.md
- Generating documents using code: generating-using-code.md
theme: readthedocs
